//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhanVienTuVan.VanPhongService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VanPhongService.IChoThueVanPhongService")]
    public interface IChoThueVanPhongService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDanhSachPhong", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDanhSachPhongResponse")]
        Entities.eVanPhong[] LayDanhSachPhong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDanhSachPhong", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDanhSachPhongResponse")]
        System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDanhSachPhongAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongTrong", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongTrongResponse")]
        Entities.eVanPhong[] LayDSVanPhongTrong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongTrong", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongTrongResponse")]
        System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDSVanPhongTrongAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongDangChoThue", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongDangChoThueResponse")]
        Entities.eVanPhong[] LayDSVanPhongDangChoThue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongDangChoThue", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSVanPhongDangChoThueResponse")]
        System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDSVanPhongDangChoThueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/DangNhap", ReplyAction="http://tempuri.org/IChoThueVanPhongService/DangNhapResponse")]
        bool DangNhap(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/DangNhap", ReplyAction="http://tempuri.org/IChoThueVanPhongService/DangNhapResponse")]
        System.Threading.Tasks.Task<bool> DangNhapAsync(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayNhanVienDangNhap", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayNhanVienDangNhapResponse")]
        Entities.eNhanVien LayNhanVienDangNhap(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayNhanVienDangNhap", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayNhanVienDangNhapResponse")]
        System.Threading.Tasks.Task<Entities.eNhanVien> LayNhanVienDangNhapAsync(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSKhachHangDangThue", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSKhachHangDangThueResponse")]
        Entities.eKhachHang[] LayDSKhachHangDangThue(string maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSKhachHangDangThue", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSKhachHangDangThueResponse")]
        System.Threading.Tasks.Task<Entities.eKhachHang[]> LayDSKhachHangDangThueAsync(string maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/TaoPhieuKiemTra", ReplyAction="http://tempuri.org/IChoThueVanPhongService/TaoPhieuKiemTraResponse")]
        void TaoPhieuKiemTra(Entities.ePhieuYeuCauKiemTraPhong p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/TaoPhieuKiemTra", ReplyAction="http://tempuri.org/IChoThueVanPhongService/TaoPhieuKiemTraResponse")]
        System.Threading.Tasks.Task TaoPhieuKiemTraAsync(Entities.ePhieuYeuCauKiemTraPhong p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/CapNhatPhieuKiemTra", ReplyAction="http://tempuri.org/IChoThueVanPhongService/CapNhatPhieuKiemTraResponse")]
        bool CapNhatPhieuKiemTra(Entities.ePhieuYeuCauKiemTraPhong p, bool tinhTrangPhong, int maNVKyThuat, string ghiChu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/CapNhatPhieuKiemTra", ReplyAction="http://tempuri.org/IChoThueVanPhongService/CapNhatPhieuKiemTraResponse")]
        System.Threading.Tasks.Task<bool> CapNhatPhieuKiemTraAsync(Entities.ePhieuYeuCauKiemTraPhong p, bool tinhTrangPhong, int maNVKyThuat, string ghiChu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuDaDuyet", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuDaDuyetResponse")]
        Entities.ePhieuYeuCauKiemTraPhong[] LayDSPhieuDaDuyet(string maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuDaDuyet", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuDaDuyetResponse")]
        System.Threading.Tasks.Task<Entities.ePhieuYeuCauKiemTraPhong[]> LayDSPhieuDaDuyetAsync(string maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuChuaDuyet", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuChuaDuyetResponse")]
        Entities.ePhieuYeuCauKiemTraPhong[] LayDSPhieuChuaDuyet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuChuaDuyet", ReplyAction="http://tempuri.org/IChoThueVanPhongService/LayDSPhieuChuaDuyetResponse")]
        System.Threading.Tasks.Task<Entities.ePhieuYeuCauKiemTraPhong[]> LayDSPhieuChuaDuyetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChoThueVanPhongServiceChannel : NhanVienTuVan.VanPhongService.IChoThueVanPhongService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChoThueVanPhongServiceClient : System.ServiceModel.ClientBase<NhanVienTuVan.VanPhongService.IChoThueVanPhongService>, NhanVienTuVan.VanPhongService.IChoThueVanPhongService {
        
        public ChoThueVanPhongServiceClient() {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoThueVanPhongServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.eVanPhong[] LayDanhSachPhong() {
            return base.Channel.LayDanhSachPhong();
        }
        
        public System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDanhSachPhongAsync() {
            return base.Channel.LayDanhSachPhongAsync();
        }
        
        public Entities.eVanPhong[] LayDSVanPhongTrong() {
            return base.Channel.LayDSVanPhongTrong();
        }
        
        public System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDSVanPhongTrongAsync() {
            return base.Channel.LayDSVanPhongTrongAsync();
        }
        
        public Entities.eVanPhong[] LayDSVanPhongDangChoThue() {
            return base.Channel.LayDSVanPhongDangChoThue();
        }
        
        public System.Threading.Tasks.Task<Entities.eVanPhong[]> LayDSVanPhongDangChoThueAsync() {
            return base.Channel.LayDSVanPhongDangChoThueAsync();
        }
        
        public bool DangNhap(string taiKhoan, string matKhau) {
            return base.Channel.DangNhap(taiKhoan, matKhau);
        }
        
        public System.Threading.Tasks.Task<bool> DangNhapAsync(string taiKhoan, string matKhau) {
            return base.Channel.DangNhapAsync(taiKhoan, matKhau);
        }
        
        public Entities.eNhanVien LayNhanVienDangNhap(string taiKhoan, string matKhau) {
            return base.Channel.LayNhanVienDangNhap(taiKhoan, matKhau);
        }
        
        public System.Threading.Tasks.Task<Entities.eNhanVien> LayNhanVienDangNhapAsync(string taiKhoan, string matKhau) {
            return base.Channel.LayNhanVienDangNhapAsync(taiKhoan, matKhau);
        }
        
        public Entities.eKhachHang[] LayDSKhachHangDangThue(string maPhong) {
            return base.Channel.LayDSKhachHangDangThue(maPhong);
        }
        
        public System.Threading.Tasks.Task<Entities.eKhachHang[]> LayDSKhachHangDangThueAsync(string maPhong) {
            return base.Channel.LayDSKhachHangDangThueAsync(maPhong);
        }
        
        public void TaoPhieuKiemTra(Entities.ePhieuYeuCauKiemTraPhong p) {
            base.Channel.TaoPhieuKiemTra(p);
        }
        
        public System.Threading.Tasks.Task TaoPhieuKiemTraAsync(Entities.ePhieuYeuCauKiemTraPhong p) {
            return base.Channel.TaoPhieuKiemTraAsync(p);
        }
        
        public bool CapNhatPhieuKiemTra(Entities.ePhieuYeuCauKiemTraPhong p, bool tinhTrangPhong, int maNVKyThuat, string ghiChu) {
            return base.Channel.CapNhatPhieuKiemTra(p, tinhTrangPhong, maNVKyThuat, ghiChu);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatPhieuKiemTraAsync(Entities.ePhieuYeuCauKiemTraPhong p, bool tinhTrangPhong, int maNVKyThuat, string ghiChu) {
            return base.Channel.CapNhatPhieuKiemTraAsync(p, tinhTrangPhong, maNVKyThuat, ghiChu);
        }
        
        public Entities.ePhieuYeuCauKiemTraPhong[] LayDSPhieuDaDuyet(string maPhong) {
            return base.Channel.LayDSPhieuDaDuyet(maPhong);
        }
        
        public System.Threading.Tasks.Task<Entities.ePhieuYeuCauKiemTraPhong[]> LayDSPhieuDaDuyetAsync(string maPhong) {
            return base.Channel.LayDSPhieuDaDuyetAsync(maPhong);
        }
        
        public Entities.ePhieuYeuCauKiemTraPhong[] LayDSPhieuChuaDuyet() {
            return base.Channel.LayDSPhieuChuaDuyet();
        }
        
        public System.Threading.Tasks.Task<Entities.ePhieuYeuCauKiemTraPhong[]> LayDSPhieuChuaDuyetAsync() {
            return base.Channel.LayDSPhieuChuaDuyetAsync();
        }
    }
}
