//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhanVienTuVan.VanPhongService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VanPhongService.IChoThueVanPhongService")]
    public interface IChoThueVanPhongService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/DoWork", ReplyAction="http://tempuri.org/IChoThueVanPhongService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChoThueVanPhongService/DoWork", ReplyAction="http://tempuri.org/IChoThueVanPhongService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChoThueVanPhongServiceChannel : NhanVienTuVan.VanPhongService.IChoThueVanPhongService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChoThueVanPhongServiceClient : System.ServiceModel.ClientBase<NhanVienTuVan.VanPhongService.IChoThueVanPhongService>, NhanVienTuVan.VanPhongService.IChoThueVanPhongService {
        
        public ChoThueVanPhongServiceClient() {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoThueVanPhongServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoThueVanPhongServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
